kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain  # Useful in case you delete the PersistentVolumeClaim
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-035361f0eab2bcccf
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/dynamic_provisioning"
